import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { Button, Container } from "@mantine/core";

import { api } from "../utils/api";
import HeaderMenu from "../components/index/HeaderMenu";
import DashboardNavbar from "../components/dashboard/DashboardNavbar";

type Props = {
  children: JSX.Element | JSX.Element[];
};
const DashboardLayout = (props: Props): JSX.Element => {
  const { children } = props;
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderMenu />
      <div>
        <DashboardNavbar />
        <Container>{children}</Container>
      </div>
    </>
  );
};

export default DashboardLayout;
