name: build-deploy

on:
  push:
    branches: ["prod"]
    paths: ["prisma/**"]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.deploy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/generate.fitness.deploy:prod
